services:
  mongodb:
    env_file:
      - ./.env.dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    ports:
      - "${MONGODB_PORT}:27017"

  backend:
    restart: no
    build:
      context: ./backend
    env_file:
      - ./.env.dev
    environment:
      - BACKEND_CORS_ORIGINS="http://localhost:3000,https://localhost:3000"
      - MONGODB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    command: ["fastapi", "run", "--reload", "app/main.py"]
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    ports:
      - "8000:8000"

  frontend:
    restart: no
    build:
      context: ./frontend
      target: builder
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    develop:
      watch:
        - path: ./frontend/src
          action: sync
          target: /app/src
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
    ports:
      - "3000:5173"
