services:
  mongodb:
    image: mongo:${MONGODB_VERSION:-8.0.12}
    restart: always
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  backend:
    image: "${DOCKER_IMAGE_BACKEND}:${TAG:-latest}"
    restart: always
    build:
      context: ./backend
    env_file:
      - ./.env
      - ./backend/.env
    environment:
      - MONGODB_SERVER=${MONGODB_SERVER}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    command: ["fastapi", "run", "app/main.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 20s
      timeout: 5s
      retries: 5
    depends_on:
      - mongodb
    networks:
      - app_network

  frontend:
    image: "${DOCKER_IMAGE_FRONTEND}:${TAG:-latest}"
    restart: always
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge
