[project]
name = "research-agent"
version = "0.1.0"
description = "An intelligent agent for automating literature review and scientific discovery: finds, analyzes, and summarizes research papers."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
