/**
 * This file was auto-generated by running `pnpm run generate:models`.
 */

import type { components } from "./openapi.gen";

export type Attachment = components["schemas"]["Attachment"];
export type Body_upload_files_api_v1_uploads_post = components["schemas"]["Body_upload_files_api_v1_uploads_post"];
export type Body_upload_paper_api_v1_papers_upload_post = components["schemas"]["Body_upload_paper_api_v1_papers_upload_post"];
export type ChatRequest = components["schemas"]["ChatRequest"];
export type ChatResponse = components["schemas"]["ChatResponse"];
export type CollectionCreate = components["schemas"]["CollectionCreate"];
export type CollectionResponse = components["schemas"]["CollectionResponse"];
export type CollectionUpdate = components["schemas"]["CollectionUpdate"];
export type ConversationCreate = components["schemas"]["ConversationCreate"];
export type ConversationDB = components["schemas"]["ConversationDB"];
export type ConversationUpdate = components["schemas"]["ConversationUpdate"];
export type CrawlerConfigCreate = components["schemas"]["CrawlerConfigCreate"];
export type CrawlerConfigResponse = components["schemas"]["CrawlerConfigResponse"];
export type CrawlerConfigUpdate = components["schemas"]["CrawlerConfigUpdate"];
export type CrawlerJobCreate = components["schemas"]["CrawlerJobCreate"];
export type CrawlerJobResponse = components["schemas"]["CrawlerJobResponse"];
export type CrawlerJobUpdate = components["schemas"]["CrawlerJobUpdate"];
export type CreateResponse = components["schemas"]["CreateResponse"];
export type DeleteResponse = components["schemas"]["DeleteResponse"];
export type HTTPValidationError = components["schemas"]["HTTPValidationError"];
export type JobStatus = components["schemas"]["JobStatus"];
export type MessageCreate = components["schemas"]["MessageCreate"];
export type MessageDB = components["schemas"]["MessageDB"];
export type MessageFilePart = components["schemas"]["MessageFilePart"];
export type MessageReasoningPart = components["schemas"]["MessageReasoningPart"];
export type MessageTextPart = components["schemas"]["MessageTextPart"];
export type MessageToolCallPart = components["schemas"]["MessageToolCallPart"];
export type MessageToolResultPart = components["schemas"]["MessageToolResultPart"];
export type PaperContent = components["schemas"]["PaperContent"];
export type PaperCreate = components["schemas"]["PaperCreate"];
export type PaperResponse = components["schemas"]["PaperResponse"];
export type PaperSource = components["schemas"]["PaperSource"];
export type PaperUpdate = components["schemas"]["PaperUpdate"];
export type Response_ConversationDB_ = components["schemas"]["Response_ConversationDB_"];
export type Response_MessageDB_ = components["schemas"]["Response_MessageDB_"];
export type Response_NoneType_ = components["schemas"]["Response_NoneType_"];
export type Response_list_Attachment__ = components["schemas"]["Response_list_Attachment__"];
export type Response_list_ConversationDB__ = components["schemas"]["Response_list_ConversationDB__"];
export type Response_list_MessageDB__ = components["schemas"]["Response_list_MessageDB__"];
export type Role = components["schemas"]["Role"];
export type ToolResultOutput = components["schemas"]["ToolResultOutput"];
export type UpdateResponse = components["schemas"]["UpdateResponse"];
export type ValidationError = components["schemas"]["ValidationError"];
