/**
 * This file was auto-generated by running `npm run generate:models`.
 */

import type { components } from "./openapi.gen";

export type AttachmentCreate = components["schemas"]["AttachmentCreate"];
export type AttachmentDB = components["schemas"]["AttachmentDB"];
export type Body_upload_files_api_v1_uploads_post = components["schemas"]["Body_upload_files_api_v1_uploads_post"];
export type ChatRequest = components["schemas"]["ChatRequest"];
export type ChatResponse = components["schemas"]["ChatResponse"];
export type ConversationCreate = components["schemas"]["ConversationCreate"];
export type ConversationDB = components["schemas"]["ConversationDB"];
export type ConversationUpdate = components["schemas"]["ConversationUpdate"];
export type CrawlerConfig = components["schemas"]["CrawlerConfig"];
export type CrawlerConfigCreate = components["schemas"]["CrawlerConfigCreate"];
export type CrawlerConfigUpdate = components["schemas"]["CrawlerConfigUpdate"];
export type CrawlerJob = components["schemas"]["CrawlerJob"];
export type CrawlerJobCreate = components["schemas"]["CrawlerJobCreate"];
export type CrawlerJobUpdate = components["schemas"]["CrawlerJobUpdate"];
export type CreateResponse = components["schemas"]["CreateResponse"];
export type DeleteResponse = components["schemas"]["DeleteResponse"];
export type HTTPValidationError = components["schemas"]["HTTPValidationError"];
export type JobStatus = components["schemas"]["JobStatus"];
export type MessageCreate = components["schemas"]["MessageCreate"];
export type MessageDB = components["schemas"]["MessageDB"];

// Use schemas from OpenAPI, but extend Paper to match backend PaperDB model
// The backend returns PaperDB which has different fields than the OpenAPI Paper schema
export type PaperBase = components["schemas"]["Paper"];

// PaperContentDB - should use schema from OpenAPI once types are regenerated
// TODO: After regenerating OpenAPI types with `npm run generate:all`, replace with:
// export type PaperContentDB = components["schemas"]["PaperContentDB"];
// For now, define based on backend app/types.py PaperContentDB model
export type PaperContentDB = {
  id: string;
  paper_id: string;
  section_name: string;
  section_index: number | null;
  chunk_index: number | null;
  content: string;
  token_count: number | null;
  embedding_vector: number[] | null;
  extra_metadata: Record<string, unknown> | null;
  created_at: string;
};

// Paper type - extends OpenAPI Paper schema but overrides fields to match backend PaperDB
export type Paper = Omit<PaperBase, "_id" | "url" | "pdf_url" | "venues" | "sections" | "source" | "source_id"> & {
  id: string;  // Backend uses 'id', not '_id'
  venue: string | null;  // Backend has single venue string, not array
  abstract: string | null;  // Backend has abstract as direct field
  source_type: string;  // Backend has source_type instead of source
  source_url: string | null;  // Backend has source_url, not url/pdf_url
  file_path: string | null;
  parsed: boolean;
  contents: PaperContentDB[];  // Backend has contents array with PaperContentDB
  collection_ids?: string[];  // IDs of collections this paper belongs to
  collection_names?: string[];  // Names of collections this paper belongs to
};

export type PaperCreate = components["schemas"]["PaperCreate"];
export type PaperSection = components["schemas"]["PaperSection"];
export type PaperSource = components["schemas"]["PaperSource"];
export type PaperUpdate = components["schemas"]["PaperUpdate"];

// Collection types (will be in OpenAPI after regeneration, but defining manually for now)
export interface Collection {
  id: string;
  name: string;
  description: string | null;
  created_at: string;
  updated_at: string;
  paper_count: number;
}

export interface CollectionCreate {
  name: string;
  description?: string | null;
}

export interface CollectionUpdate {
  name?: string | null;
  description?: string | null;
}
export type Response_ConversationDB_ = components["schemas"]["Response_ConversationDB_"];
export type Response_MessageDB_ = components["schemas"]["Response_MessageDB_"];
export type Response_NoneType_ = components["schemas"]["Response_NoneType_"];
export type Response_list_AttachmentCreate__ = components["schemas"]["Response_list_AttachmentCreate__"];
export type Response_list_ConversationDB__ = components["schemas"]["Response_list_ConversationDB__"];
export type Response_list_MessageDB__ = components["schemas"]["Response_list_MessageDB__"];
export type Role = components["schemas"]["Role"];
export type UpdateResponse = components["schemas"]["UpdateResponse"];
export type ValidationError = components["schemas"]["ValidationError"];
