/**
 * This file was auto-generated by running `npm run generate:models`.
 */

import type { components } from "./openapi.gen";

export type AttachmentCreate = components["schemas"]["AttachmentCreate"];
export type AttachmentDB = components["schemas"]["AttachmentDB"];
export type ChatRequest = components["schemas"]["ChatRequest"];
export type ChatResponse = components["schemas"]["ChatResponse"];
export type ConversationCreate = components["schemas"]["ConversationCreate"];
export type ConversationDB = components["schemas"]["ConversationDB"];
export type ConversationUpdate = components["schemas"]["ConversationUpdate"];
export type CrawlerConfig = components["schemas"]["CrawlerConfig"];
export type CrawlerConfigCreate = components["schemas"]["CrawlerConfigCreate"];
export type CrawlerConfigUpdate = components["schemas"]["CrawlerConfigUpdate"];
export type CrawlerJob = components["schemas"]["CrawlerJob"];
export type CrawlerJobCreate = components["schemas"]["CrawlerJobCreate"];
export type CrawlerJobUpdate = components["schemas"]["CrawlerJobUpdate"];
export type CreateResponse = components["schemas"]["CreateResponse"];
export type DeleteResponse = components["schemas"]["DeleteResponse"];
export type HTTPValidationError = components["schemas"]["HTTPValidationError"];
export type JobStatus = components["schemas"]["JobStatus"];
export type MessageCreate = components["schemas"]["MessageCreate"];
export type MessageDB = components["schemas"]["MessageDB"];
export type Paper = components["schemas"]["Paper"];
export type PaperCreate = components["schemas"]["PaperCreate"];
export type PaperSection = components["schemas"]["PaperSection"];
export type PaperSource = components["schemas"]["PaperSource"];
export type PaperUpdate = components["schemas"]["PaperUpdate"];
export type Response_ConversationDB_ = components["schemas"]["Response_ConversationDB_"];
export type Response_MessageDB_ = components["schemas"]["Response_MessageDB_"];
export type Response_NoneType_ = components["schemas"]["Response_NoneType_"];
export type Response_list_ConversationDB__ = components["schemas"]["Response_list_ConversationDB__"];
export type Response_list_MessageDB__ = components["schemas"]["Response_list_MessageDB__"];
export type Role = components["schemas"]["Role"];
export type UpdateResponse = components["schemas"]["UpdateResponse"];
export type ValidationError = components["schemas"]["ValidationError"];
