/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Send a message and get an AI response in a conversation.
         */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Chat
         * @description Send a message and get a streaming AI response in a conversation.
         */
        post: operations["stream_chat_api_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversations
         * @description List all conversations.
         */
        get: operations["get_conversations_api_v1_conversations_get"];
        put?: never;
        /**
         * Create Conversation
         * @description Create a new conversation.
         */
        post: operations["create_conversation_api_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Message
         * @description Create a new message in a new or existing conversation.
         */
        post: operations["create_message_api_v1_conversations_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/messages/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Last Message
         * @description Get the latest message in a conversation.
         */
        get: operations["get_last_message_api_v1_conversations_messages_last_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Message
         * @description Get a specific message by ID.
         */
        get: operations["get_message_api_v1_conversations_messages__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Get a specific conversation.
         */
        get: operations["get_conversation_api_v1_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description Delete a conversation.
         */
        delete: operations["delete_conversation_api_v1_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Conversation
         * @description Update a conversation.
         */
        patch: operations["update_conversation_api_v1_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Messages
         * @description List all messages in a conversation.
         */
        get: operations["get_messages_api_v1_conversations__conversation_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crawlers/configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Crawler Configs
         * @description List all crawler configurations.
         */
        get: operations["get_crawler_configs_api_v1_crawlers_configs_get"];
        put?: never;
        /**
         * Create Crawler Config
         * @description Create a new crawler configuration.
         */
        post: operations["create_crawler_config_api_v1_crawlers_configs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crawlers/configs/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Crawler Config
         * @description Get a specific crawler configuration.
         */
        get: operations["get_crawler_config_api_v1_crawlers_configs__config_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Crawler Config
         * @description Delete a crawler configuration.
         */
        delete: operations["delete_crawler_config_api_v1_crawlers_configs__config_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Crawler Config
         * @description Update a crawler configuration.
         */
        patch: operations["update_crawler_config_api_v1_crawlers_configs__config_id__patch"];
        trace?: never;
    };
    "/api/v1/crawlers/configs/name/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Crawler Config By Name
         * @description Get a specific crawler configuration by name.
         */
        get: operations["get_crawler_config_by_name_api_v1_crawlers_configs_name__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crawlers/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Crawler Jobs */
        get: operations["get_crawler_jobs_api_v1_crawlers_jobs_get"];
        put?: never;
        /**
         * Create Crawler Job
         * @description Create and start a new crawler job.
         */
        post: operations["create_crawler_job_api_v1_crawlers_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crawlers/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Crawler Job
         * @description Get a crawler job.
         */
        get: operations["get_crawler_job_api_v1_crawlers_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Crawler Job
         * @description Delete a crawler job.
         */
        delete: operations["delete_crawler_job_api_v1_crawlers_jobs__job_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Crawler Job
         * @description Update a crawler job.
         */
        patch: operations["update_crawler_job_api_v1_crawlers_jobs__job_id__patch"];
        trace?: never;
    };
    "/api/v1/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Papers
         * @description List all papers.
         */
        get: operations["get_papers_api_v1_papers_get"];
        put?: never;
        /**
         * Create Paper
         * @description Create a new paper.
         */
        post: operations["create_paper_api_v1_papers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Paper
         * @description Get a specific paper.
         */
        get: operations["get_paper_api_v1_papers__paper_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Paper
         * @description Delete a paper.
         */
        delete: operations["delete_paper_api_v1_papers__paper_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Paper
         * @description Update a paper.
         */
        patch: operations["update_paper_api_v1_papers__paper_id__patch"];
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Files
         * @description Upload files and return attachment metadata.
         */
        post: operations["upload_files_api_v1_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint with API Information
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoints.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttachmentCreate
         * @description Model for creating a new attachment.
         */
        AttachmentCreate: {
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Path */
            path: string;
            /** Size */
            size: number;
        };
        /**
         * AttachmentDB
         * @description Model for attachment stored in database.
         */
        AttachmentDB: {
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Path */
            path: string;
            /** Size */
            size: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_upload_files_api_v1_uploads_post */
        Body_upload_files_api_v1_uploads_post: {
            /** Files */
            files: string[];
        };
        /**
         * ChatRequest
         * @description Model for chat request.
         */
        ChatRequest: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
        };
        /**
         * ChatResponse
         * @description Model for chat response model.
         */
        ChatResponse: {
            data: components["schemas"]["MessageDB"];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * ConversationCreate
         * @description Model for creating a new conversation.
         */
        ConversationCreate: {
            /** Name */
            name: string;
            /** Id */
            id?: string | null;
        };
        /**
         * ConversationDB
         * @description Model for conversation stored in database.
         */
        ConversationDB: {
            /** Name */
            name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ConversationUpdate
         * @description Model for updating an existing conversation.
         */
        ConversationUpdate: {
            /** Name */
            name?: string | null;
        };
        /**
         * CrawlerConfig
         * @description Model for crawler configuration stored in database.
         */
        CrawlerConfig: {
            /** Name */
            name: string;
            source: components["schemas"]["PaperSource"];
            /**
             * Rate Limit
             * @default 10
             */
            rate_limit: number;
            /**
             * Max Delay
             * @default 60
             */
            max_delay: number;
            /**
             * Max Attempts
             * @default 3
             */
            max_attempts: number;
            /**
             * Max Concurrent
             * @default 10
             */
            max_concurrent: number;
            /**
             * Output Dir
             * @default crawled_papers
             */
            output_dir: string;
            /** Id */
            _id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CrawlerConfigCreate
         * @description Model for creating a new crawler configuration.
         */
        CrawlerConfigCreate: {
            /** Name */
            name: string;
            source: components["schemas"]["PaperSource"];
            /**
             * Rate Limit
             * @default 10
             */
            rate_limit: number;
            /**
             * Max Delay
             * @default 60
             */
            max_delay: number;
            /**
             * Max Attempts
             * @default 3
             */
            max_attempts: number;
            /**
             * Max Concurrent
             * @default 10
             */
            max_concurrent: number;
            /**
             * Output Dir
             * @default crawled_papers
             */
            output_dir: string;
        };
        /**
         * CrawlerConfigUpdate
         * @description Model for updating an existing crawler configuration.
         */
        CrawlerConfigUpdate: {
            /** Name */
            name?: string | null;
            source?: components["schemas"]["PaperSource"] | null;
            /** Rate Limit */
            rate_limit?: number | null;
            /** Max Delay */
            max_delay?: number | null;
            /** Max Attempts */
            max_attempts?: number | null;
            /** Max Concurrent */
            max_concurrent?: number | null;
            /** Output Dir */
            output_dir?: string | null;
        };
        /**
         * CrawlerJob
         * @description Model for crawler job stored in database.
         */
        CrawlerJob: {
            /** Config Name */
            config_name: string;
            /** Query */
            query?: string | null;
            /** Urls */
            urls?: string[] | null;
            /** Max Papers */
            max_papers?: number | null;
            /** Id */
            _id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** @default pending */
            status: components["schemas"]["JobStatus"];
        };
        /**
         * CrawlerJobCreate
         * @description Model for creating a new crawler job.
         */
        CrawlerJobCreate: {
            /** Config Name */
            config_name: string;
            /** Query */
            query?: string | null;
            /** Urls */
            urls?: string[] | null;
            /** Max Papers */
            max_papers?: number | null;
        };
        /**
         * CrawlerJobUpdate
         * @description Model for updating an existing crawler job.
         */
        CrawlerJobUpdate: {
            /** Query */
            query?: string | null;
            /** Urls */
            urls?: string[] | null;
            /** Max Papers */
            max_papers?: number | null;
        };
        /**
         * CreateResponse
         * @description Response model for create operations.
         */
        CreateResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Created Count */
            created_count: number;
            /** Created Ids */
            created_ids: string[];
        };
        /**
         * DeleteResponse
         * @description Response model for delete operations.
         */
        DeleteResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Deleted Count */
            deleted_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobStatus
         * @description Status of processing a job.
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "completed" | "failed";
        /**
         * MessageCreate
         * @description Model for creating a new message.
         */
        MessageCreate: {
            /** Content */
            content: string;
            role: components["schemas"]["Role"];
            /** Attachments */
            attachments?: components["schemas"]["AttachmentCreate"][];
        };
        /**
         * MessageDB
         * @description Model for message stored in database.
         */
        MessageDB: {
            /** Content */
            content: string;
            role: components["schemas"]["Role"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Attachments */
            attachments?: components["schemas"]["AttachmentDB"][];
        };
        /**
         * Paper
         * @description Model for paper stored in database.
         */
        Paper: {
            /** Title */
            title: string;
            /** Authors */
            authors: string[];
            source: components["schemas"]["PaperSource"];
            /** Source Id */
            source_id: string;
            /** Year */
            year?: number | null;
            /** Url */
            url?: string | null;
            /** Pdf Url */
            pdf_url?: string | null;
            /** Local Pdf Path */
            local_pdf_path?: string | null;
            /** Venues */
            venues?: string[];
            /** Sections */
            sections?: {
                [key: string]: components["schemas"]["PaperSection"];
            };
            /** Job Id */
            job_id?: string | null;
            /** Id */
            _id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PaperCreate
         * @description Model for creating a new paper.
         */
        PaperCreate: {
            /** Title */
            title: string;
            /** Authors */
            authors: string[];
            source: components["schemas"]["PaperSource"];
            /** Source Id */
            source_id: string;
            /** Year */
            year?: number | null;
            /** Url */
            url?: string | null;
            /** Pdf Url */
            pdf_url?: string | null;
            /** Local Pdf Path */
            local_pdf_path?: string | null;
            /** Venues */
            venues?: string[];
            /** Sections */
            sections?: {
                [key: string]: components["schemas"]["PaperSection"];
            };
            /** Job Id */
            job_id?: string | null;
        };
        /**
         * PaperSection
         * @description Model for representing a section of a research paper.
         */
        PaperSection: {
            /** Title */
            title: string;
            /** Content */
            content: string;
            /**
             * Level
             * @default 1
             */
            level: number;
        };
        /**
         * PaperSource
         * @description Source of a paper.
         * @enum {string}
         */
        PaperSource: "acl_anthology";
        /**
         * PaperUpdate
         * @description Model for updating an existing paper.
         */
        PaperUpdate: {
            /** Title */
            title?: string | null;
            /** Authors */
            authors?: string[] | null;
            source?: components["schemas"]["PaperSource"] | null;
            /** Source Id */
            source_id?: string | null;
            /** Year */
            year?: number | null;
            /** Url */
            url?: string | null;
            /** Pdf Url */
            pdf_url?: string | null;
            /** Local Pdf Path */
            local_pdf_path?: string | null;
            /** Venues */
            venues?: string[] | null;
            /** Sections */
            sections?: {
                [key: string]: components["schemas"]["PaperSection"];
            } | null;
            /** Job Id */
            job_id?: string | null;
        };
        /** Response[ConversationDB] */
        Response_ConversationDB_: {
            data: components["schemas"]["ConversationDB"];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** Response[MessageDB] */
        Response_MessageDB_: {
            data: components["schemas"]["MessageDB"];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** Response[NoneType] */
        Response_NoneType_: {
            /** Data */
            data: null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** Response[list[AttachmentCreate]] */
        Response_list_AttachmentCreate__: {
            /** Data */
            data: components["schemas"]["AttachmentCreate"][];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** Response[list[ConversationDB]] */
        Response_list_ConversationDB__: {
            /** Data */
            data: components["schemas"]["ConversationDB"][];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** Response[list[MessageDB]] */
        Response_list_MessageDB__: {
            /** Data */
            data: components["schemas"]["MessageDB"][];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * Role
         * @description Role of a message sender.
         * @enum {string}
         */
        Role: "user" | "assistant";
        /**
         * UpdateResponse
         * @description Response model for update operations.
         */
        UpdateResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Matched Count */
            matched_count: number;
            /** Modified Count */
            modified_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_chat_api_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversations_api_v1_conversations_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_ConversationDB__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ConversationDB_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_api_v1_conversations_messages_post: {
        parameters: {
            query: {
                conversation_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_MessageDB_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_last_message_api_v1_conversations_messages_last_get: {
        parameters: {
            query: {
                conversation_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_MessageDB_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_message_api_v1_conversations_messages__message_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_MessageDB_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_v1_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ConversationDB_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_v1_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_api_v1_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ConversationDB_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_api_v1_conversations__conversation_id__messages_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_MessageDB__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crawler_configs_api_v1_crawlers_configs_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlerConfig"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_crawler_config_api_v1_crawlers_configs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlerConfigCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crawler_config_api_v1_crawlers_configs__config_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlerConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_crawler_config_api_v1_crawlers_configs__config_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_crawler_config_api_v1_crawlers_configs__config_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlerConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crawler_config_by_name_api_v1_crawlers_configs_name__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlerConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crawler_jobs_api_v1_crawlers_jobs_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                status?: components["schemas"]["JobStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlerJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_crawler_job_api_v1_crawlers_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlerJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crawler_job_api_v1_crawlers_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlerJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_crawler_job_api_v1_crawlers_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_crawler_job_api_v1_crawlers_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlerJobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_papers_api_v1_papers_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paper"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_paper_api_v1_papers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_api_v1_papers__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paper"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_paper_api_v1_papers__paper_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_paper_api_v1_papers__paper_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_files_api_v1_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_files_api_v1_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_AttachmentCreate__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
