/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Send a message and get an AI response in a conversation.
         */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Chat
         * @description Send a message and get a streaming AI response in a conversation.
         */
        post: operations["stream_chat_api_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversations
         * @description List all conversations.
         */
        get: operations["get_conversations_api_v1_conversations_get"];
        put?: never;
        /**
         * Create Conversation
         * @description Create a new conversation.
         */
        post: operations["create_conversation_api_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Message
         * @description Create a new message in a new or existing conversation.
         */
        post: operations["create_message_api_v1_conversations_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/messages/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Last Message
         * @description Get the latest message in a conversation.
         */
        get: operations["get_last_message_api_v1_conversations_messages_last_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Message
         * @description Get a specific message by ID.
         */
        get: operations["get_message_api_v1_conversations_messages__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Get a specific conversation.
         */
        get: operations["get_conversation_api_v1_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description Delete a conversation.
         */
        delete: operations["delete_conversation_api_v1_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Conversation
         * @description Update a conversation.
         */
        patch: operations["update_conversation_api_v1_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Messages
         * @description List all messages in a conversation.
         */
        get: operations["get_messages_api_v1_conversations__conversation_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crawlers/configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Crawler Configs
         * @description List all crawler configurations.
         */
        get: operations["get_crawler_configs_api_v1_crawlers_configs_get"];
        put?: never;
        /**
         * Create Crawler Config
         * @description Create a new crawler configuration.
         */
        post: operations["create_crawler_config_api_v1_crawlers_configs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crawlers/configs/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Crawler Config
         * @description Get a specific crawler configuration.
         */
        get: operations["get_crawler_config_api_v1_crawlers_configs__config_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Crawler Config
         * @description Delete a crawler configuration.
         */
        delete: operations["delete_crawler_config_api_v1_crawlers_configs__config_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Crawler Config
         * @description Update a crawler configuration.
         */
        patch: operations["update_crawler_config_api_v1_crawlers_configs__config_id__patch"];
        trace?: never;
    };
    "/api/v1/crawlers/configs/name/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Crawler Config By Name
         * @description Get a specific crawler configuration by name.
         */
        get: operations["get_crawler_config_by_name_api_v1_crawlers_configs_name__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crawlers/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Crawler Jobs */
        get: operations["get_crawler_jobs_api_v1_crawlers_jobs_get"];
        put?: never;
        /**
         * Create Crawler Job
         * @description Create and start a new crawler job.
         */
        post: operations["create_crawler_job_api_v1_crawlers_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crawlers/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Crawler Job
         * @description Get a crawler job.
         */
        get: operations["get_crawler_job_api_v1_crawlers_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Crawler Job
         * @description Delete a crawler job.
         */
        delete: operations["delete_crawler_job_api_v1_crawlers_jobs__job_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Crawler Job
         * @description Update a crawler job.
         */
        patch: operations["update_crawler_job_api_v1_crawlers_jobs__job_id__patch"];
        trace?: never;
    };
    "/api/v1/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Papers
         * @description List all papers from Postgres.
         */
        get: operations["get_papers_api_v1_papers_get"];
        put?: never;
        /**
         * Create Paper
         * @description Create a new paper stored in Postgres.
         */
        post: operations["create_paper_api_v1_papers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Paper
         * @description Upload a PDF paper file with optional metadata.
         *
         *     If metadata is provided by the user, it will be used.
         *     If metadata is missing, it will be extracted from the PDF.
         *     User-provided metadata takes precedence over extracted metadata.
         */
        post: operations["upload_paper_api_v1_papers_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Paper
         * @description Get a specific paper from Postgres.
         */
        get: operations["get_paper_api_v1_papers__paper_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Paper
         * @description Delete a paper from Postgres.
         */
        delete: operations["delete_paper_api_v1_papers__paper_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Paper
         * @description Update a paper in Postgres.
         */
        patch: operations["update_paper_api_v1_papers__paper_id__patch"];
        trace?: never;
    };
    "/api/v1/papers/by-job/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Papers By Job
         * @description Get all papers created by a specific crawler job.
         */
        get: operations["get_papers_by_job_api_v1_papers_by_job__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/analytics/papers-per-month": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Papers Per Month
         * @description Get count of papers per month for analytics.
         *     Returns list of dicts with 'month' (1-12) and 'papers' (count).
         */
        get: operations["get_papers_per_month_api_v1_papers_analytics_papers_per_month_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Collections
         * @description List all collections.
         */
        get: operations["get_collections_api_v1_collections_get"];
        put?: never;
        /**
         * Create Collection
         * @description Create a new collection.
         */
        post: operations["create_collection_api_v1_collections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Collection
         * @description Get a specific collection.
         */
        get: operations["get_collection_api_v1_collections__collection_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Collection
         * @description Delete a collection.
         */
        delete: operations["delete_collection_api_v1_collections__collection_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Collection
         * @description Update a collection.
         */
        patch: operations["update_collection_api_v1_collections__collection_id__patch"];
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Collection Papers
         * @description Get all papers in a collection.
         */
        get: operations["get_collection_papers_api_v1_collections__collection_id__papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Paper To Collection
         * @description Add a paper to a collection.
         */
        post: operations["add_paper_to_collection_api_v1_collections__collection_id__papers__paper_id__post"];
        /**
         * Remove Paper From Collection
         * @description Remove a paper from a collection.
         */
        delete: operations["remove_paper_from_collection_api_v1_collections__collection_id__papers__paper_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/analytics/papers-by-collection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Papers By Collection
         * @description Get count of papers per collection for analytics.
         *     Returns list of dicts with 'name' (collection name) and 'value' (paper count).
         */
        get: operations["get_papers_by_collection_api_v1_collections_analytics_papers_by_collection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Files
         * @description Upload files and return attachment metadata.
         */
        post: operations["upload_files_api_v1_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint with API Information
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoints.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Attachment
         * @description Model for attachments stored in JSONB.
         */
        Attachment: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Content Type */
            content_type: string;
        };
        /** Body_upload_files_api_v1_uploads_post */
        Body_upload_files_api_v1_uploads_post: {
            /** Files */
            files: string[];
        };
        /** Body_upload_paper_api_v1_papers_upload_post */
        Body_upload_paper_api_v1_papers_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Title */
            title?: string | null;
            /** Abstract */
            abstract?: string | null;
            /** Doi */
            doi?: string | null;
            /** Year */
            year?: number | null;
            /**
             * Authors
             * @description Comma-separated
             */
            authors?: string | null;
            /**
             * Keywords
             * @description Comma-separated
             */
            keywords?: string | null;
        };
        /**
         * ChatRequest
         * @description Model for chat request.
         */
        ChatRequest: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
        };
        /**
         * ChatResponse
         * @description Model for chat response model.
         */
        ChatResponse: {
            data: components["schemas"]["MessageDB"];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * CollectionCreate
         * @description Model for creating a new collection.
         */
        CollectionCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * CollectionResponse
         * @description Response model for collection matching ORM Collection structure.
         */
        CollectionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Paper Count
             * @default 0
             */
            paper_count: number;
        };
        /**
         * CollectionUpdate
         * @description Model for updating an existing collection.
         */
        CollectionUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * ConversationCreate
         * @description Model for creating a new conversation.
         */
        ConversationCreate: {
            /** Name */
            name: string;
            /** Id */
            id?: string | null;
        };
        /**
         * ConversationDB
         * @description Model for conversation stored in database.
         */
        ConversationDB: {
            /** Name */
            name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ConversationUpdate
         * @description Model for updating an existing conversation.
         */
        ConversationUpdate: {
            /** Name */
            name?: string | null;
        };
        /**
         * CrawlerConfigCreate
         * @description Model for creating a new crawler configuration.
         */
        CrawlerConfigCreate: {
            /** Name */
            name: string;
            source: components["schemas"]["PaperSource"];
            /**
             * Rate Limit
             * @default 10
             */
            rate_limit: number;
            /**
             * Max Delay
             * @default 60
             */
            max_delay: number;
            /**
             * Max Attempts
             * @default 3
             */
            max_attempts: number;
            /**
             * Max Concurrent
             * @default 10
             */
            max_concurrent: number;
            /**
             * Output Dir
             * @default crawled_papers
             */
            output_dir: string;
        };
        /**
         * CrawlerConfigResponse
         * @description Response model for crawler configuration from SQLAlchemy.
         */
        CrawlerConfigResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            source: components["schemas"]["PaperSource"];
            /** Rate Limit */
            rate_limit: number;
            /** Max Delay */
            max_delay: number;
            /** Max Attempts */
            max_attempts: number;
            /** Max Concurrent */
            max_concurrent: number;
            /** Output Dir */
            output_dir: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CrawlerConfigUpdate
         * @description Model for updating an existing crawler configuration.
         */
        CrawlerConfigUpdate: {
            /** Name */
            name?: string | null;
            source?: components["schemas"]["PaperSource"] | null;
            /** Rate Limit */
            rate_limit?: number | null;
            /** Max Delay */
            max_delay?: number | null;
            /** Max Attempts */
            max_attempts?: number | null;
            /** Max Concurrent */
            max_concurrent?: number | null;
            /** Output Dir */
            output_dir?: string | null;
        };
        /**
         * CrawlerJobCreate
         * @description Model for creating a new crawler job.
         */
        CrawlerJobCreate: {
            /**
             * Config Name
             * @default default_acl_anthology
             */
            config_name: string;
            /** Urls */
            urls?: string[] | null;
            /** Query */
            query?: string | null;
            /** Max Papers */
            max_papers?: number | null;
        };
        /**
         * CrawlerJobResponse
         * @description Response model for crawler job from SQLAlchemy.
         */
        CrawlerJobResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Config Name */
            config_name: string;
            /** Urls */
            urls?: string[] | null;
            /** Max Papers */
            max_papers?: number | null;
            status: components["schemas"]["JobStatus"];
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CrawlerJobUpdate
         * @description Model for updating an existing crawler job.
         */
        CrawlerJobUpdate: {
            /** Urls */
            urls?: string[] | null;
            /** Max Papers */
            max_papers?: number | null;
        };
        /**
         * CreateResponse
         * @description Response model for create operations.
         */
        CreateResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Created Count */
            created_count: number;
            /** Created Ids */
            created_ids: string[];
        };
        /**
         * DeleteResponse
         * @description Response model for delete operations.
         */
        DeleteResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Deleted Count */
            deleted_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobStatus
         * @description Status of processing a job.
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "completed" | "failed";
        /**
         * MessageCreate
         * @description Model for creating a new message.
         */
        MessageCreate: {
            /** @default user */
            role: components["schemas"]["Role"];
            /** Content */
            content: (components["schemas"]["MessageTextPart"] | components["schemas"]["MessageFilePart"] | components["schemas"]["MessageReasoningPart"] | components["schemas"]["MessageToolCallPart"] | components["schemas"]["MessageToolResultPart"])[];
            /** Id */
            id?: string | null;
            /** Attachments */
            attachments?: components["schemas"]["Attachment"][];
        };
        /**
         * MessageDB
         * @description Model for message stored in database.
         */
        MessageDB: {
            /** @default user */
            role: components["schemas"]["Role"];
            /** Content */
            content: (components["schemas"]["MessageTextPart"] | components["schemas"]["MessageFilePart"] | components["schemas"]["MessageReasoningPart"] | components["schemas"]["MessageToolCallPart"] | components["schemas"]["MessageToolResultPart"])[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Attachments */
            attachments?: components["schemas"]["Attachment"][];
        };
        /**
         * MessageFilePart
         * @description File content part of a message.
         */
        MessageFilePart: {
            /**
             * Type
             * @default file
             * @constant
             */
            type: "file";
            /** Filename */
            filename?: string | null;
            /** Data */
            data: string;
            /** Media Type */
            media_type: string;
        };
        /**
         * MessageReasoningPart
         * @description Reasoning content part of a message.
         */
        MessageReasoningPart: {
            /**
             * Type
             * @default reasoning
             * @constant
             */
            type: "reasoning";
            /** Text */
            text: string;
        };
        /**
         * MessageTextPart
         * @description Text content part of a message.
         */
        MessageTextPart: {
            /**
             * Type
             * @default text
             * @constant
             */
            type: "text";
            /** Text */
            text: string;
        };
        /**
         * MessageToolCallPart
         * @description Tool call content part of a message.
         */
        MessageToolCallPart: {
            /**
             * Type
             * @default tool-call
             * @constant
             */
            type: "tool-call";
            /** Tool Call Id */
            tool_call_id: string;
            /** Tool Name */
            tool_name: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
        };
        /**
         * MessageToolResultPart
         * @description Tool result content part of a message.
         */
        MessageToolResultPart: {
            /**
             * Type
             * @default tool-result
             * @constant
             */
            type: "tool-result";
            /** Tool Call Id */
            tool_call_id: string;
            /** Tool Name */
            tool_name: string;
            output: components["schemas"]["ToolResultOutput"];
        };
        /**
         * PaperContent
         * @description Model for paper content matching database PaperContent structure.
         */
        PaperContent: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /** Section Name */
            section_name: string;
            /** Section Index */
            section_index?: number | null;
            /** Chunk Index */
            chunk_index?: number | null;
            /** Content */
            content: string;
            /** Token Count */
            token_count?: number | null;
            /** Embedding Vector */
            embedding_vector?: number[] | null;
            /** Extra Metadata */
            extra_metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PaperCreate
         * @description Model for creating a new paper.
         */
        PaperCreate: {
            /** Title */
            title: string;
            /** Authors */
            authors?: string[] | null;
            /** Year */
            year?: number | null;
            /** Venue */
            venue?: string | null;
            /** Abstract */
            abstract?: string | null;
            /** Source Type */
            source_type: string;
            /** Source Url */
            source_url?: string | null;
            /** File Path */
            file_path?: string | null;
            /** Contents */
            contents?: components["schemas"]["PaperContent"][];
            /** Job Id */
            job_id?: string | null;
        };
        /**
         * PaperResponse
         * @description Response model for paper matching ORM Paper structure (for API responses).
         */
        PaperResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Authors */
            authors?: string[] | null;
            /** Year */
            year?: number | null;
            /** Venue */
            venue?: string | null;
            /** Abstract */
            abstract?: string | null;
            /** Source Type */
            source_type: string;
            /** Source Url */
            source_url?: string | null;
            /** File Path */
            file_path?: string | null;
            /** Job Id */
            job_id?: string | null;
            /** Parsed */
            parsed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Contents */
            contents?: components["schemas"]["PaperContent"][];
            /**
             * Collection Ids
             * @description IDs of collections this paper belongs to
             */
            collection_ids?: string[];
            /**
             * Collection Names
             * @description Names of collections this paper belongs to
             */
            collection_names?: string[];
        };
        /**
         * PaperSource
         * @description Source of a paper.
         * @enum {string}
         */
        PaperSource: "acl_anthology";
        /**
         * PaperUpdate
         * @description Model for updating an existing paper.
         */
        PaperUpdate: {
            /** Title */
            title?: string | null;
            /** Authors */
            authors?: string[] | null;
            /** Year */
            year?: number | null;
            /** Venue */
            venue?: string | null;
            /** Abstract */
            abstract?: string | null;
            /** Source Type */
            source_type?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** File Path */
            file_path?: string | null;
            /** Contents */
            contents?: components["schemas"]["PaperContent"][] | null;
            /** Job Id */
            job_id?: string | null;
        };
        /** Response[ConversationDB] */
        Response_ConversationDB_: {
            data: components["schemas"]["ConversationDB"];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** Response[MessageDB] */
        Response_MessageDB_: {
            data: components["schemas"]["MessageDB"];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** Response[NoneType] */
        Response_NoneType_: {
            /** Data */
            data: null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** Response[list[Attachment]] */
        Response_list_Attachment__: {
            /** Data */
            data: components["schemas"]["Attachment"][];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** Response[list[ConversationDB]] */
        Response_list_ConversationDB__: {
            /** Data */
            data: components["schemas"]["ConversationDB"][];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** Response[list[MessageDB]] */
        Response_list_MessageDB__: {
            /** Data */
            data: components["schemas"]["MessageDB"][];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * Role
         * @description Role of a message sender.
         * @enum {string}
         */
        Role: "user" | "assistant";
        /**
         * ToolResultOutput
         * @description Result of a tool call. Supports multiple output types.
         */
        ToolResultOutput: {
            /**
             * Type
             * @enum {string}
             */
            type: "text" | "json" | "error-text" | "error-json" | "content" | "sub-agent";
            /** Value */
            value: unknown;
        };
        /**
         * UpdateResponse
         * @description Response model for update operations.
         */
        UpdateResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Matched Count */
            matched_count: number;
            /** Modified Count */
            modified_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_chat_api_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversations_api_v1_conversations_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_ConversationDB__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ConversationDB_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_api_v1_conversations_messages_post: {
        parameters: {
            query: {
                conversation_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_MessageDB_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_last_message_api_v1_conversations_messages_last_get: {
        parameters: {
            query: {
                conversation_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_MessageDB_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_message_api_v1_conversations_messages__message_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_MessageDB_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_v1_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ConversationDB_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_v1_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_api_v1_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ConversationDB_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_api_v1_conversations__conversation_id__messages_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_MessageDB__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crawler_configs_api_v1_crawlers_configs_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlerConfigResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_crawler_config_api_v1_crawlers_configs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlerConfigCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crawler_config_api_v1_crawlers_configs__config_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlerConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_crawler_config_api_v1_crawlers_configs__config_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_crawler_config_api_v1_crawlers_configs__config_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlerConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crawler_config_by_name_api_v1_crawlers_configs_name__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlerConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crawler_jobs_api_v1_crawlers_jobs_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                status?: components["schemas"]["JobStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlerJobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_crawler_job_api_v1_crawlers_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlerJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crawler_job_api_v1_crawlers_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlerJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_crawler_job_api_v1_crawlers_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_crawler_job_api_v1_crawlers_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlerJobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_papers_api_v1_papers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperResponse"][];
                };
            };
        };
    };
    create_paper_api_v1_papers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_paper_api_v1_papers_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_paper_api_v1_papers_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_api_v1_papers__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_paper_api_v1_papers__paper_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_paper_api_v1_papers__paper_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_papers_by_job_api_v1_papers_by_job__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_papers_per_month_api_v1_papers_analytics_papers_per_month_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collections_api_v1_collections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionResponse"][];
                };
            };
        };
    };
    create_collection_api_v1_collections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_api_v1_collections__collection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_collection_api_v1_collections__collection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_collection_api_v1_collections__collection_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_papers_api_v1_collections__collection_id__papers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_paper_to_collection_api_v1_collections__collection_id__papers__paper_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_paper_from_collection_api_v1_collections__collection_id__papers__paper_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_papers_by_collection_api_v1_collections_analytics_papers_by_collection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    upload_files_api_v1_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_files_api_v1_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_Attachment__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
