import fs from "fs"

import { Project } from "ts-morph"

const schemasSymbols = new Project()
  .addSourceFileAtPath("src/shared/api/openapi.gen.ts")
  .getInterfaceOrThrow("components")
  .getPropertyOrThrow("schemas")
  .getType()
  .getProperties()

const schemasNames = schemasSymbols.map((s) => s.getName())

const aliases = schemasNames
  .map((name) => `export type ${name} = components["schemas"]["${name}"]`)
  .join("\n")

fs.writeFileSync(
  "src/shared/api/models.ts",
  `/**
 * This file was auto-generated by running \`npm run generate:models\`.
 */` + `\n\nimport type { components } from "./openapi.gen"\n\n${aliases}\n`
)
