"""merged migrations

Revision ID: 51b314b942f3
Revises: 29fe1954e0b1
Create Date: 2025-12-13 13:16:57.505802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b314b942f3'
down_revision: Union[str, Sequence[str], None] = '29fe1954e0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_crawler_job_updated_at'), 'crawler_job', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_message_content_tool_calls'), table_name='message', postgresql_ops={'content': 'jsonb_path_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_message_content_tool_calls'), 'message', ['content'], unique=False, postgresql_ops={'content': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_crawler_job_updated_at'), table_name='crawler_job')
    # ### end Alembic commands ###
